spring:

  security:
    user:
      name: user
      password: pass

  data:
    mongodb:
      uri: mongodb://mongo/employee?retryWrites=true&w=majority
      repositories:
        enabled: true
      auto-index-creation: true
      database: employee

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.example.demo.event"
          deserializer:
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer